before_script:
 - apt-get update --yes
 - apt-get install --yes cmake

stages:
 - build
 - test

build:
  stage: build
  tags:
    - Ubuntu1804-64bit
  script:
    - apt-get update && apt-get install -qy libxml2-utils libxml2-dev
    - cd src
    - cmake .
    - make 
  artifacts:
    untracked: true

test:
  stage: test
  tags:
    - Ubuntu1804-64bit
  script:
    - make test
  dependencies:
    - build
