/*
 * generated by Xtext 2.19.0
 */
package org.xtext.paretoalgebra.calculator.ide


/**
 * Use this class to register ide components.
 */
class CalculatorIdeModule extends AbstractCalculatorIdeModule {
}
